name: sandanter_customer_transaction_prediction
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pandas=2.2.2
  - numpy=1.26.4
  - scikit-learn=1.6.1
  - xgboost=2.1.4
  - joblib=1.4.2
  - matplotlib=3.9.2
  - seaborn=0.13.2
  - pip
  - pip:
      - imbalanced-learn==0.12.3
